title: 'Creative Coding'
author:
  name: Marcin
  email: marcin@creativecoding.dev
taxonomies:
  - category
  - tag
metadata:
  description: 'Creative coding, TouchDesigner, etc.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
